version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: gunicorn questionnaires.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env